version: '3'
services:
  react_image_compressor:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/node/app
  
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - react_image_compressor